name: CI/CD Vite Project

on:
  push:
    branches:
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm ci

    - name: Build project
      run: |
        npm run build

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PRODLIKE }}
        SERVER: ${{ secrets.PRODLIKE_SERVER }} # Mengambil server IP dari GitHub Secrets
        USERNAME: ${{ secrets.PRODLIKE_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$SERVER" >> ~/.ssh/known_hosts

        # Masuk ke folder mathbot dan transfer hanya file hasil build menggunakan rsync
           rsync -avz --delete --exclude='node_modules' --exclude='.git' dist/ package.json package-lock.json $USERNAME@$SERVER:~/sibiti-frontend
         
    - name: Restart PM2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_PRODLIKE }}
        SERVER: ${{ secrets.PRODLIKE_SERVER }} # Mengambil server IP dari GitHub Secrets
        USERNAME: ${{ secrets.PRODLIKE_USERNAME }}
        
      run: |
        ssh $USERNAME@$SERVER '
          cd ~/sibiti-frontend;
          if pm2 list | grep -q "smansa-prodlike-frontend"; then
            pm2 restart smansa-prodlike-frontend;
          else
            pm2 start npm --name smansa-prodlike-frontend -- run start;
          fi
          pm2 save; # Simpan konfigurasi PM2 untuk memastikan proses otomatis di-restart setelah server reboot
        '

      
